### ISSUE TITLE
吉言的往右

### ISSUE THREAD

**Issue by LongLiveGPCR** [THZrry/demos_in_csdn#1]
lol

**Comment by LongLiveGPCR** [comment]
> 什么玩意才看到，我还是不希望看到人身攻击甚至人肉，我也翻到你X了我也不想打扰你，这件事还是这样结束吧，我们互不打扰。

6啊，我为什么要开盒你
还有，我好像没有X帐号吧，lol

**Comment by THZrry** [comment]
不想和你互相打扰，能别在我的仓库讲这些吗，我看到的和你同一个名字同一个头像的，你要是说不是你也没事，这不是重点，好吗

**Comment by LongLiveGPCR** [comment]
> 不想和你互相打扰，能别在我的仓库讲这些吗，我看到的和你同一个名字同一个头像的，你要是说不是你也没事，这不是重点，好吗

ok，但是有些往右非要在你发的issue里辩论我也没办法。。
